### ISSUE TITLE
Archive this?

### ISSUE THREAD

**Issue by chee** [Financial-Times/eslint-config-origami-component#8]
It used to be used in components, but now the eslint config used for those is in `obt`. It's only used in `o-ads-embed`, `o-lazy-load`, `o-permutive` and `o-stepped-progress`, `occ`, and `o-spacing`.

It's added to the `devDependencies` by [the `obt component boilerplate`](https://github.com/Financial-Times/origami-build-tools/blob/09d68db1fcaa175e96b6c687a927e6b2be54f7ab/templates/component-boilerplate/package-json.js) but `obt` [uses](https://github.com/Financial-Times/origami-build-tools/blob/cf219aa5029754feb0f98c63db87f2af4a439786/lib/tasks/verify-javascript.js) its [own config](https://github.com/Financial-Times/origami-build-tools/blob/cf219aa5029754feb0f98c63db87f2af4a439786/config/.eslintrc.js)

**Comment by chee** [comment]
@Financial-Times/origami-core

**Comment by JakeChampion** [comment]
I think the rationale behind having the configuration separated from obt was to make it possible to integrate the configuration with Editor ESLint plugins.
Is there a way to get the eslint config from `obt` for use with Editor ESLint plugins? If there is a way, then we should definitely look to archive/deprecate/dead this 👍

**Comment by JakeChampion** [comment]
This is now being used by all our origami components so that we can have eslint editor plugins working. The new OBT will also be using this config as well :-) https://github.com/Financial-Times/origami-build-tools/pull/713

**Comment by chee** [comment]
yay
